apiVersion: v1
kind: Service
metadata:
  name: app-hr
spec:
  selector:
    app: hr
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr
  template:
    metadata:
      labels:
        app: hr
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo '<h1>HR DEPARTMENT (K8s)</h1><p>Internal Secure Service</p>' > /usr/share/nginx/html/index.html"]
---
apiVersion: v1
kind: Service
metadata:
  name: app-finance
spec:
  selector:
    app: finance
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo '<h1>FINANCE DEPT (K8s)</h1><p>Restricted Access</p>' > /usr/share/nginx/html/index.html"]