apiVersion: v1
kind: Service
metadata:
  name: edge-metrics
spec:
  selector:
    app: nfv-edge
  ports:
    - port: 9113
      name: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfv-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfv-edge
  template:
    metadata:
      labels:
        app: nfv-edge
    spec:
      volumes:
        - name: gateway-config-vol
          configMap:
            name: gateway-conf
      containers:
      # -----------------------------------------------
      # CONTAINER 1: ZeroTier (The Network Interface)
      # -----------------------------------------------
      - name: zerotier
        image: zerotier/zerotier:latest
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "SYS_ADMIN"]
        env:
          - name: ZT_NETWORKS
            value: temptemptemp # <--- PASTE ID HERE
        
        # --- NEW: AUTO-JOIN LOGIC ---
        lifecycle:
          postStart:
            exec:
              command: 
                - "/bin/sh"
                - "-c"
                - "sleep 5; zerotier-cli join $ZT_NETWORKS"
        # ----------------------------

      # -----------------------------------------------
      # CONTAINER 2: Nginx Gateway (The Router)
      # -----------------------------------------------
      - name: nginx
        image: nginx:alpine
        volumeMounts:
          - name: gateway-config-vol
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf

      # -----------------------------------------------
      # CONTAINER 3: Exporter (The Translator)
      # -----------------------------------------------
      - name: exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
          - -nginx.scrape-uri=http://127.0.0.1:80/stub_status