apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-cluster-role
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - namespaces
      - nodes
      - services
      - endpoints
    verbs: ["get", "watch", "list"]

  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs: ["get", "watch", "list"]

  - apiGroups: ["events.k8s.io"]
    resources:
      - events
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filebeat-cluster-role
subjects:
  - kind: ServiceAccount
    name: filebeat-sa
    namespace: default
